name: Use action to upload example notebooks to TileDB Cloud
on:
  push:
    paths:
      - '.github/workflows/upload-notebooks-action.yml'
      - 'examples/**'
      - 'tiledb/**'
      - 'setup.py'
  pull_request:
    paths:
      - '.github/workflows/upload-notebooks-action.yml'
      - 'examples/**'
      - 'tiledb/**'
      - 'setup.py'
  workflow_dispatch:
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Upload notebooks
      uses: jdblischak/github-actions/upload-notebooks@upload-notebooks
      with:
        notebooks: ["examples/OMETiff-convertor-demo.ipynb", "examples/OMEZarr-convertor-demo.ipynb"]
        TILEDB_CLOUD_TOKEN: ${{ secrets.TILEDB_CLOUD_TOKEN }}
        TILEDB_CLOUD_NAMESPACE: jdblischak
        TILEDB_CLOUD_STORAGE_PATH: s3://tiledb-cloud-jdblischak/notebooks
        TILEDB_CLOUD_STORAGE_CREDENTIAL_NAME: personal-aws
