name: Use action to upload example notebooks to TileDB Cloud
on:
  push:
    paths:
      - '.github/workflows/upload-notebooks-action.yml'
      - 'examples/**'
      - 'tiledb/**'
      - 'setup.py'
  pull_request:
    paths:
      - '.github/workflows/upload-notebooks-action.yml'
      - 'examples/**'
      - 'tiledb/**'
      - 'setup.py'
  workflow_dispatch:
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Upload notebooks
      uses: jdblischak/github-actions/upload-notebooks@upload-notebooks-pr
      with:
        notebooks_local: examples/OMETiff-convertor-demo.ipynb examples/OMEZarr-convertor-demo.ipynb
        notebooks_remote: tiledb://s3://tiledb-cloud-jdblischak/notebooks/OMETiff-convertor-demo tiledb://s3://tiledb-cloud-jdblischak/notebooks/OMEZarr-convertor-demo
        TILEDB_CLOUD_TOKEN: ${{ secrets.TILEDB_CLOUD_TOKEN }}
        TILEDB_CLOUD_STORAGE_CREDENTIAL_NAME: personal-aws
