name: Upload example notebooks to TileDB Cloud
on:
  push:
    paths:
      - '.github/scripts/environment.yml'
      - '.github/workflows/upload-notebooks.yml'
      - 'examples/**'
      - 'tiledb/**'
      - 'setup.py'
  pull_request:
    paths:
      - '.github/scripts/environment.yml'
      - '.github/workflows/upload-notebooks.yml'
      - 'examples/**'
      - 'tiledb/**'
      - 'setup.py'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3
    - name: Install Conda environment with Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: .github/scripts/environment.yml
        cache-env: true
    - name: Install tiledb-bioimg package
      run: pip install --no-deps .[full]
    - name: Run notebook examples
      run: pytest --nbmake examples
  upload:
    # remove filters for initial testing from a feature branch
    #if: github.branch == 'main' && github.event_name != 'pull_request'
    needs: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: pip install tiledb-cloud
    - name: Upload notebooks
      env:
        TILEDB_CLOUD_TOKEN: ${{ secrets.TILEDB_CLOUD_TOKEN }}
        TILEDB_CLOUD_NAMESPACE: jdblischak
        TILEDB_CLOUD_STORAGE_PATH: s3://tiledb-cloud-jdblischak/notebooks
        TILEDB_CLOUD_STORAGE_CREDENTIAL_NAME: personal-aws
      run: |
        for notebook in examples/*.ipynb
        do
          echo "Uploading $notebook"
          python .github/scripts/upload-notebook.py "$notebook"
        done
